add debug

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -35,5 +35,8 @@ jobs:
       - name: Generate Prisma client
         run: npx prisma generate
 
+      - name: Debug prisma client
+        run: ls -R generated || echo "generated not found"
+
       - name: Run lint
         run: pnpm lint
